[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.12"
serde = "1.0.142"
serde_derive = "1.0.142"
serde_json = "1.0.83"
sha2 = "0.10.2"
indicatif = "0.17.0"